const FLAGS: Record<string, string> = {
  'Alžírsko': '🇩🇿',
  'Anglie': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'Argentina': '🇦🇷',
  'Austrálie': '🇦🇺',
  'Belgie': '🇧🇪',
  'Bosna a Hercegovina': '🇧🇦',
  'Brazílie': '🇧🇷',
  'Chorvatsko': '🇭🇷',
  'Curacao': '🇨🇼',
  'DR Kongo': '🇨🇩',
  'Egypt': '🇪🇬',
  'Ekvádor': '🇪🇨',
  'Francie': '🇫🇷',
  'Ghana': '🇬🇭',
  'Haiti': '🇭🇹',
  'Irák': '🇮🇶',
  'Írán': '🇮🇷',
  'Japonsko': '🇯🇵',
  'Jihoafrická republika': '🇿🇦',
  'Jižní Korea': '🇰🇷',
  'Jordánsko': '🇯🇴',
  'Kanada': '🇨🇦',
  'Kapverdy': '🇨🇻',
  'Katar': '🇶🇦',
  'Kolumbie': '🇨🇴',
  'Maroko': '🇲🇦',
  'Mexiko': '🇲🇽',
  'Německo': '🇩🇪',
  'Nizozemsko': '🇳🇱',
  'Norsko': '🇳🇴',
  'Nový Zéland': '🇳🇿',
  'Panama': '🇵🇦',
  'Paraguay': '🇵🇾',
  'Pobřeží slonoviny': '🇨🇮',
  'Portugalsko': '🇵🇹',
  'Rakousko': '🇦🇹',
  'Saúdská Arábie': '🇸🇦',
  'Senegal': '🇸🇳',
  'Skotsko': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'Španělsko': '🇪🇸',
  'Švédsko': '🇸🇪',
  'Švýcarsko': '🇨🇭',
  'Tunisko': '🇹🇳',
  'Turecko': '🇹🇷',
  'Uruguay': '🇺🇾',
  'USA': '🇺🇸',
  'Uzbekistán': '🇺🇿',
  'Česko': '🇨🇿',
}

const ABBR: Record<string, string> = {
  'Alžírsko': 'ALG',
  'Anglie': 'ENG',
  'Argentina': 'ARG',
  'Austrálie': 'AUS',
  'Belgie': 'BEL',
  'Bosna a Hercegovina': 'BIH',
  'Brazílie': 'BRA',
  'Chorvatsko': 'CRO',
  'Curacao': 'CUW',
  'DR Kongo': 'COD',
  'Egypt': 'EGY',
  'Ekvádor': 'ECU',
  'Francie': 'FRA',
  'Ghana': 'GHA',
  'Haiti': 'HAI',
  'Irák': 'IRQ',
  'Írán': 'IRN',
  'Japonsko': 'JPN',
  'Jihoafrická republika': 'RSA',
  'Jižní Korea': 'KOR',
  'Jordánsko': 'JOR',
  'Kanada': 'CAN',
  'Kapverdy': 'CPV',
  'Katar': 'QAT',
  'Kolumbie': 'COL',
  'Maroko': 'MAR',
  'Mexiko': 'MEX',
  'Německo': 'GER',
  'Nizozemsko': 'NED',
  'Norsko': 'NOR',
  'Nový Zéland': 'NZL',
  'Panama': 'PAN',
  'Paraguay': 'PAR',
  'Pobřeží slonoviny': 'CIV',
  'Portugalsko': 'POR',
  'Rakousko': 'AUT',
  'Saúdská Arábie': 'KSA',
  'Senegal': 'SEN',
  'Skotsko': 'SCO',
  'Španělsko': 'ESP',
  'Švédsko': 'SWE',
  'Švýcarsko': 'SUI',
  'Tunisko': 'TUN',
  'Turecko': 'TUR',
  'Uruguay': 'URU',
  'USA': 'USA',
  'Uzbekistán': 'UZB',
  'Česko': 'CZE',
}

export function flag(team: string): string {
  return FLAGS[team] ?? ''
}

export function abbr(team: string): string {
  return ABBR[team] ?? team.slice(0, 3).toUpperCase()
}

export function teamWithFlag(team: string): string {
  const f = FLAGS[team]
  return f ? `${f} ${team}` : team
}
