alter table public.matches add column if not exists col_index int;

update public.matches set col_index = 4 where home_team = 'Mexiko' and away_team = 'Jihoafrická republika';
update public.matches set col_index = 8 where home_team = 'Jižní Korea' and away_team = 'Česko';
update public.matches set col_index = 12 where home_team = 'Kanada' and away_team = 'Bosna a Hercegovina';
update public.matches set col_index = 16 where home_team = 'USA' and away_team = 'Paraguay';
update public.matches set col_index = 20 where home_team = 'Katar' and away_team = 'Švýcarsko';
update public.matches set col_index = 24 where home_team = 'Brazílie' and away_team = 'Maroko';
update public.matches set col_index = 26 where home_team = 'Haiti' and away_team = 'Skotsko';
update public.matches set col_index = 30 where home_team = 'Austrálie' and away_team = 'Turecko';
update public.matches set col_index = 34 where home_team = 'Německo' and away_team = 'Curacao';
update public.matches set col_index = 38 where home_team = 'Nizozemsko' and away_team = 'Japonsko';
update public.matches set col_index = 42 where home_team = 'Pobřeží slonoviny' and away_team = 'Ekvádor';
update public.matches set col_index = 44 where home_team = 'Švédsko' and away_team = 'Tunisko';
update public.matches set col_index = 48 where home_team = 'Španělsko' and away_team = 'Kapverdy';
update public.matches set col_index = 52 where home_team = 'Belgie' and away_team = 'Egypt';
update public.matches set col_index = 56 where home_team = 'Saúdská Arábie' and away_team = 'Uruguay';
update public.matches set col_index = 58 where home_team = 'Írán' and away_team = 'Nový Zéland';
update public.matches set col_index = 62 where home_team = 'Francie' and away_team = 'Senegal';
update public.matches set col_index = 66 where home_team = 'Irák' and away_team = 'Norsko';
update public.matches set col_index = 68 where home_team = 'Argentina' and away_team = 'Alžírsko';
update public.matches set col_index = 72 where home_team = 'Rakousko' and away_team = 'Jordánsko';
update public.matches set col_index = 76 where home_team = 'Portugalsko' and away_team = 'DR Kongo';
update public.matches set col_index = 80 where home_team = 'Anglie' and away_team = 'Chorvatsko';
update public.matches set col_index = 84 where home_team = 'Ghana' and away_team = 'Panama';
update public.matches set col_index = 86 where home_team = 'Uzbekistán' and away_team = 'Kolumbie';
update public.matches set col_index = 90 where home_team = 'Česko' and away_team = 'Jihoafrická republika';
update public.matches set col_index = 94 where home_team = 'Švýcarsko' and away_team = 'Bosna a Hercegovina';
update public.matches set col_index = 98 where home_team = 'Kanada' and away_team = 'Katar';
update public.matches set col_index = 100 where home_team = 'Mexiko' and away_team = 'Jižní Korea';
update public.matches set col_index = 104 where home_team = 'USA' and away_team = 'Austrálie';
update public.matches set col_index = 108 where home_team = 'Skotsko' and away_team = 'Maroko';
update public.matches set col_index = 110 where home_team = 'Brazílie' and away_team = 'Haiti';
update public.matches set col_index = 112 where home_team = 'Turecko' and away_team = 'Paraguay';
update public.matches set col_index = 116 where home_team = 'Nizozemsko' and away_team = 'Švédsko';
update public.matches set col_index = 120 where home_team = 'Německo' and away_team = 'Pobřeží slonoviny';
update public.matches set col_index = 124 where home_team = 'Ekvádor' and away_team = 'Curacao';
update public.matches set col_index = 128 where home_team = 'Tunisko' and away_team = 'Japonsko';
update public.matches set col_index = 132 where home_team = 'Španělsko' and away_team = 'Saúdská Arábie';
update public.matches set col_index = 136 where home_team = 'Belgie' and away_team = 'Írán';
update public.matches set col_index = 140 where home_team = 'Uruguay' and away_team = 'Kapverdy';
update public.matches set col_index = 142 where home_team = 'Nový Zéland' and away_team = 'Egypt';
update public.matches set col_index = 146 where home_team = 'Argentina' and away_team = 'Rakousko';
update public.matches set col_index = 150 where home_team = 'Francie' and away_team = 'Irák';
update public.matches set col_index = 154 where home_team = 'Norsko' and away_team = 'Senegal';
update public.matches set col_index = 156 where home_team = 'Jordánsko' and away_team = 'Alžírsko';
update public.matches set col_index = 160 where home_team = 'Portugalsko' and away_team = 'Uzbekistán';
update public.matches set col_index = 164 where home_team = 'Anglie' and away_team = 'Ghana';
update public.matches set col_index = 168 where home_team = 'Panama' and away_team = 'Chorvatsko';
update public.matches set col_index = 170 where home_team = 'Kolumbie' and away_team = 'DR Kongo';
update public.matches set col_index = 174 where home_team = 'Švýcarsko' and away_team = 'Kanada';
update public.matches set col_index = 178 where home_team = 'Bosna a Hercegovina' and away_team = 'Katar';
update public.matches set col_index = 182 where home_team = 'Skotsko' and away_team = 'Brazílie';
update public.matches set col_index = 184 where home_team = 'Maroko' and away_team = 'Haiti';
update public.matches set col_index = 188 where home_team = 'Česko' and away_team = 'Mexiko';
update public.matches set col_index = 190 where home_team = 'Jihoafrická republika' and away_team = 'Jižní Korea';
update public.matches set col_index = 194 where home_team = 'Ekvádor' and away_team = 'Německo';
update public.matches set col_index = 198 where home_team = 'Curacao' and away_team = 'Pobřeží slonoviny';
update public.matches set col_index = 202 where home_team = 'Tunisko' and away_team = 'Nizozemsko';
update public.matches set col_index = 204 where home_team = 'Japonsko' and away_team = 'Švédsko';
update public.matches set col_index = 206 where home_team = 'Turecko' and away_team = 'USA';
update public.matches set col_index = 208 where home_team = 'Paraguay' and away_team = 'Austrálie';
update public.matches set col_index = 212 where home_team = 'Norsko' and away_team = 'Francie';
update public.matches set col_index = 216 where home_team = 'Senegal' and away_team = 'Irák';
update public.matches set col_index = 220 where home_team = 'Uruguay' and away_team = 'Španělsko';
update public.matches set col_index = 222 where home_team = 'Kapverdy' and away_team = 'Saúdská Arábie';
update public.matches set col_index = 224 where home_team = 'Nový Zéland' and away_team = 'Belgie';
update public.matches set col_index = 226 where home_team = 'Egypt' and away_team = 'Írán';
update public.matches set col_index = 230 where home_team = 'Panama' and away_team = 'Anglie';
update public.matches set col_index = 234 where home_team = 'Chorvatsko' and away_team = 'Ghana';
update public.matches set col_index = 238 where home_team = 'Kolumbie' and away_team = 'Portugalsko';
update public.matches set col_index = 240 where home_team = 'DR Kongo' and away_team = 'Uzbekistán';
update public.matches set col_index = 242 where home_team = 'Jordánsko' and away_team = 'Argentina';
update public.matches set col_index = 244 where home_team = 'Alžírsko' and away_team = 'Rakousko';
